### ISSUE TITLE
[enhancement] README应当需要重新撰写

### ISSUE THREAD

**Issue by BobAnkh** [Kousaten/Brix#1]
README应当遵从更加开源规范的标准重新进行书写

**Comment by ResetPower** [comment]
# 回复 from ResetPower
刚刚找到一篇文章：[这里](https://www.jianshu.com/p/813b70d5b0de)
准备开始重新撰写了。

**Comment by BobAnkh** [comment]
我比较建议参考这个repo:[https://github.com/RichardLitt/standard-readme](https://github.com/RichardLitt/standard-readme)，这也是开源界比较著名的规范形式，我自己也是采用这样的架构的

**Comment by BobAnkh** [comment]
@ResetPower README的markdown语法规范不够标准，如果使用vscode编辑可以安装markdownlint插件进行检查，否则也可以使用markdownlint-cli的命令行工具，或者直接部署github action来做检查
