### ISSUE TITLE
[enhancement] About Demo

### ISSUE THREAD

**Issue by BobAnkh** [Kousaten/Brix#7]
目前我们没有办法或者说暂时没有需求去搭建demo站点，那么我们可以使用图片的方式来进行demo展示

**Comment by ResetPower** [comment]
# Roger that!
我将会在图片demo制作完毕后关闭这个issue

**Comment by BobAnkh** [comment]
> # Roger that!
> 我将会在图片demo制作完毕后关闭这个issue

记得在pr描述中可以使用`Resolves: #??`直接随pr合并时关闭对应issue
